### ISSUE TITLE
Funcube Dongle Pro Plus and GQRX

### ISSUE THREAD

**Issue by ik8ozv** [dl1ksv/gr-funcube#11] opened 2023-07-03 11:29 UTC
Hello,
i am ecountering problems when i try to run the GQRX with the FCDPP.
When i run the gqrx i see as diveces 2 FUNCUBE DONGE PRO PLUS, one called:
FUNCUBE DONGE PRO PLUS V2.0 and the other called FUNCUBE DONGE PRO PLUS V2.0  Stereo analogigo.
If i choose the first one the Gqrx chashes and closes, while if i choose the second one i hear the sond like mixed
with the Background noise. I have traed on Gnuradio with an FM broadcast radio and i can hear it cleary.
Pleas any help how to fix the problem??
Thanks
73's de Enzo IK8OZV

**Comment by dl1ksv** [comment] 2023-07-03 14:55
Duplicate of #10

**Closed by dl1ksv** 2023-07-03 14:55 UTC
